import { fetchItems } from "../../../lib/supabaseServer";
import GithubAiList from "../../../components/GithubAiList";

export const revalidate = 300;

export const metadata = {
  title: "Trending GitHub AI Repositories — BAI News",
  description:
    "Curated list of trending AI repositories on GitHub — including daily, weekly, and monthly GitHub trending AI projects, plus notable open-source AI projects with the most stars. Auto-summarized and updated continuously.",
  alternates: {
    canonical: "https://bainews.site/en/github-ai",
    languages: {
      vi: "https://bainews.site/github-ai",
      en: "https://bainews.site/en/github-ai",
    },
  },
};

export default async function GithubAiPageEN() {
  const { items = [] } = await fetchItems({
    filter: "github",
    sort: "hot",
    time: "all",
    offset: 0,
    limit: 60,
  });

  return (
    <main className="wrap">
      <header className="site-header">
        <div>
          <h1 className="site-title">
            <a href="/" style={{ textDecoration: "none", color: "inherit" }}>
              BAI News
            </a>
          </h1>
          <p className="tagline">News, summarized, with sources.</p>
        </div>
      </header>

      <section style={{ marginBottom: "1.5rem" }}>
        <h2 style={{ fontSize: "1.35rem", fontWeight: 700, marginBottom: "0.5rem" }}>
          Trending GitHub AI Repositories
        </h2>
        <p style={{ color: "var(--muted)", lineHeight: 1.6, margin: 0 }}>
          A curated feed of trending AI repositories on GitHub — covering daily, weekly, and monthly
          trending AI projects, plus the most-starred notable open-source AI projects of all time.
          Summaries are auto-generated by AI and updated continuously.
        </p>
      </section>

      <GithubAiList items={items} lang="en" />
    </main>
  );
}
