import { fetchItems } from "../../../lib/supabaseServer";
import GithubAiList from "../../../components/GithubAiList";
import SiteHeader from "../../../components/SiteHeader";
import SiteFooter from "../../../components/SiteFooter";

const LANG_LINKS = { vi: "/github-ai", en: "/en/github-ai" };

export const revalidate = 300;

export const metadata = {
  title: "Trending GitHub AI Repositories — BAI News",
  description:
    "Curated list of trending AI repositories on GitHub — including daily, weekly, and monthly GitHub trending AI projects, plus notable open-source AI projects with the most stars. Auto-summarized and updated continuously.",
  alternates: {
    canonical: "https://bainews.site/en/github-ai",
    languages: {
      vi: "https://bainews.site/github-ai",
      en: "https://bainews.site/en/github-ai",
    },
  },
};

export default async function GithubAiPageEN() {
  const { items = [] } = await fetchItems({
    filter: "github",
    sort: "hot",
    time: "all",
    offset: 0,
    limit: 60,
  });

  return (
    <>
      <SiteHeader lang="en" langLinks={LANG_LINKS} active="github" />
      <main className="page-narrow">
        <div className="page-head">
          <p className="page-kicker">Open source</p>
          <h1 className="page-title">Trending GitHub AI Repositories</h1>
          <p className="page-desc">
            A curated feed of trending AI repositories on GitHub — covering daily, weekly, and monthly
          trending AI projects, plus the most-starred notable open-source AI projects of all time.
          Summaries are auto-generated by AI and updated continuously.
          </p>
        </div>

        <GithubAiList items={items} lang="en" />
      </main>
      <SiteFooter lang="en" />
    </>
  );
}
